"use client";

import {
  Users,
  UserCheck,
  UserX,
  Ticket,
} from "lucide-react";

export default function PartnerStatsCard({ stats }) {
  const items = [
    {
      label: "Total Partners",
      value: stats.total,
      icon: Users,
      bg: "bg-blue-100",
      iconColor: "text-blue-600",
      desc: "All registered partners",
    },
    {
      label: "Active Partners",
      value: stats.active,
      icon: UserCheck,
      bg: "bg-green-100",
      iconColor: "text-green-600",
      desc: "Currently active accounts",
    },
    {
      label: "Inactive Partners",
      value: stats.inactive,
      icon: UserX,
      bg: "bg-red-100",
      iconColor: "text-red-600",
      desc: "Disabled or suspended",
    },
    {
      label: "Total Coupons",
      value: stats.totalCoupons,
      icon: Ticket,
      bg: "bg-purple-100",
      iconColor: "text-purple-600",
      desc: "Coupons generated by partners",
    },
  ];

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
      {items.map((item) => {
        const Icon = item.icon;

        return (
          <div
            key={item.label}
            className="bg-white border rounded-2xl p-5 shadow-sm hover:shadow-md transition"
          >
            {/* HEADER */}
            <div className="flex items-center gap-3 mb-3">
              <div className={`p-2 rounded-xl ${item.bg}`}>
                <Icon className={`w-5 h-5 ${item.iconColor}`} />
              </div>

              <div>
                <div className="text-sm text-gray-500">{item.label}</div>
                <div className="text-xs text-gray-400">{item.desc}</div>
              </div>
            </div>

            {/* VALUE */}
            <div className="text-3xl font-bold text-gray-900">
              {item.value}
            </div>
          </div>
        );
      })}
    </div>
  );
}